config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :customerservers

  resources :cloudservices

  resources :customers

  resources :users

  get '/home',     to: 'static_pages#home'

  get '/customers',   to: 'customers#new'

  get '/cloudservices', to: 'cloudservices#new'
 
  get '/customerservices',to: 'customerservices#new'

  get '/project',  to: 'projects#new'

  root 'sessions#new'

  post '/login',  to: 'sessions#create'
  
  get '/login',   to: 'sessions#new'

  delete '/logout',   to: 'sessions#destroy'

  get 'users/new'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user
  def home
  end

  def customers
  end

  def cloudservices
  end

  def customerservices
  end

  def projects
  end

  private

  def logged_in_user
    unless logged_in?
	flash[:danger] = "Please log in."
    redirect_to login_url
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="center jubmotron">
  <h1><center>Welcome to the Project Management</center></h1>

  <h2>
    <center>This is the internal project management system.</center>
  </h2>
<style>
ul
{
  list-style-type:none;
  margin:0px;
  padding:0px;
  width: 100%;
  background-color: #CCC;
  border: 1px solid #555;
}

li a {
  display: block;
  color: #000;
  padding: 8px 16px;
  text-decoration: none;
}
 
li {
  text-align: center;
  border-bottom: 1px solid #555;

li:last-child {
  border-bottom: none;
}
/* 鼠标移动到选项上修改背景颜色 */





li a.active {
  background-color: #4CAF50;
  color: white;
}

li a:hover:not(.active) {
  background-color: #555;
  color: white;
}

</style>
    <ul><font size="3">
	  <li><%= link_to "Customers",         customers_path    %></li>
      <li><%= link_to "Cloudservices",     cloudservices_path %></li>
      <li><%= link_to "Customerservers",   customerservers_path %></li>
	  <li><%= link_to "Projects",           projects_path %></li>
	  <li><%= link_to "Log out",      logout_path, method: "delete" %></li>
	</ul></font>


<% else %>
  <li><%= link_to "Log in", login_path %></li>
<% end %>

</div>