config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :customerservers

  resources :cloudservices

  resources :customers

  resources :users

  get '/home',     to: 'static_pages#home'

  get '/customers',   to: 'customers#new'

  get '/cloudservices', to: 'cloudservices#new'
 
  get '/customerservices',to: 'customerservices#new'

  get '/project',  to: 'projects#new'

  root 'sessions#new'

  post '/login',  to: 'sessions#create'
  
  get '/login',   to: 'sessions#new'

  delete '/logout',   to: 'sessions#destroy'

  get 'users/new'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/customerserver.rb
class Customerserver < ApplicationRecord
  validates :code, uniqueness: { case_sensitive: false }
end

app/controllers/customerservers_controller.rb
class CustomerserversController < ApplicationController
  before_action :logged_in_user
  before_action :set_customerserver, only: [:show, :edit, :update, :destroy]

  # GET /customerservers
  # GET /customerservers.json
  def index
    @customerservers = Customerserver.all
  end

  # GET /customerservers/1
  # GET /customerservers/1.json
  def show
  end

  # GET /customerservers/new
  def new
    @customerserver = Customerserver.new
  end

  # GET /customerservers/1/edit
  def edit
  end

  # POST /customerservers
  # POST /customerservers.json
  def create
    @customerserver = Customerserver.new(customerserver_params)

    respond_to do |format|
      if @customerserver.save
        format.html { redirect_to customerservers_path, notice: 'Customerserver was successfully created.' }
        format.json { render :show, status: :created, location: @customerserver }
      else
        format.html { render :new }
        format.json { render json: @customerserver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customerservers/1
  # PATCH/PUT /customerservers/1.json
  def update
    respond_to do |format|
      if @customerserver.update(customerserver_params)
        format.html { redirect_to @customerserver, notice: 'Customerserver was successfully updated.' }
        format.json { render :show, status: :ok, location: @customerserver }
      else
        format.html { render :edit }
        format.json { render json: @customerserver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customerservers/1
  # DELETE /customerservers/1.json
  def destroy
    @customerserver.destroy
    respond_to do |format|
      format.html { redirect_to customerservers_url, notice: 'Customerserver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customerserver
      @customerserver = Customerserver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customerserver_params
      params.require(:customerserver).permit(:code, :customerservice, :customer, :deadline, :our_server)
    end

    def logged_in_user
	  unless logged_in?
	    redirect_to login_url
	  end
	end
end

app/helpers/customerservers_helper.rb
module CustomerserversHelper
end

app/views/customerservers/_form.html.erb
<%= form_for(customerserver) do |f| %>
  <% if customerserver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customerserver.errors.count, "error") %> prohibited this customerserver from being saved:</h2>

      <ul>
      <% customerserver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :customerservice %>
    <%= f.text_field :customerservice %>
  </div>

  <div class="field">
    <%= f.label :customer %>
    <%= f.text_field :customer %>
  </div>

  <div class="field">
    <%= f.label :deadline %>
    <%= date_select :customerserver, :deadline %>
  </div>

  <div class="field">
    <%= f.label :our_server %>
    <%= f.text_field :our_server %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customerservers/edit.html.erb
<h1>Editing Customerserver</h1>

<%= render 'form', customerserver: @customerserver %>

<%= link_to 'Show', @customerserver %> |
<%= link_to 'Back', customerservers_path %>

app/views/customerservers/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.bootcss.com/foundation/5.5.3/css/foundation.min.css">

  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://cdn.bootcss.com/foundation/5.5.3/js/foundation.min.js"></script>
  <script src="https://cdn.bootcss.com/foundation/5.5.3/js/vendor/modernizr.js"></script>

<style>

ul.side-nav {
  position: fixed;
  left: 25px;
  top: 60px;
  background-color: #eefaff;
}
ul.side-nav {
  border-style:outset;
  border:1px solid #bbe1f1;
}
ul.side-nav {
  padding-top:25px;
  padding-bottom:25px;
  padding-right:0px;
  padding-left:0px;
}

</style>

<script>
  $(function(){
    $("input[type=button]").click(function(){
       var txt=$("input[type=text]").val();
         if($.trim(txt)!=""){
           $("table tr:not('#theader')").hide().filter(":contains('"+txt+"')").show().css("background","white");
         }else{
           $("table tr:not('#theader')").css("background","#fff").show();
         }
    });
})
</script>

</head>
<body>

<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><center>Customerservers</center></h1>
</div>
<ul class="side-nav">
  <li style="font-size: 1.5em;"><%= link_to "Customers",         customers_path    %></li>
  <li style="font-size: 1.5em;"><%= link_to "Cloudservices",     cloudservices_path %></li>
  <li style="font-size: 1.5em;"><%= link_to "Customerservers",   customerservers_path %></li>
  <li style="font-size: 1.5em;"><%= link_to "Projects",           projects_path %></li>
</ul>

<input type="text"></input>
<input type="button" value="搜索"></input>


<table class="table table-striped table-bordered table-hover tablesorter">
  <thead>
    <tr id="theader">
      <th>Code</th>
      <th>Customerservice</th>
      <th>Customer</th>
      <th>Deadline</th>
      <th>Our server</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customerservers.each do |customerserver| %>
      <tr>
        <td><%= customerserver.code %></td>
        <td><%= customerserver.customerservice %></td>
        <td><%= customerserver.customer %></td>
        <td><%= customerserver.deadline %></td>
        <td><%= customerserver.our_server %></td>
        <td><%= link_to 'Show', customerserver %></td>
        <td><%= link_to 'Edit', edit_customerserver_path(customerserver) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customerserver', new_customerserver_path %>

<br>

<%= link_to 'Our server',         cloudservices_path %>

<br>

<%= link_to 'Return to the home page', home_path    %>

</body>
</html>

app/views/customerservers/new.html.erb
<h1>New Customerserver</h1>

<%= render 'form', customerserver: @customerserver %>

<%= link_to 'Back', customerservers_path %>

app/views/customerservers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @customerserver.code %>
</p>

<p>
  <strong>Customerservice:</strong>
  <%= @customerserver.customerservice %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @customerserver.customer %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @customerserver.deadline %>
</p>

<p>
  <strong>Our server:</strong>
  <%= @customerserver.our_server %>
</p>

<%= link_to 'Edit', edit_customerserver_path(@customerserver) %> |
<%= link_to 'Back', customerservers_path %> |
<%= link_to 'Destroy', @customerserver, method: :delete, data: { confirm: 'Are you sure?' } %>