config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :customerservers

  resources :cloudservices

  resources :customers

  resources :users

  get '/home',     to: 'static_pages#home'

  get '/customers',   to: 'customers#new'

  get '/cloudservices', to: 'cloudservices#new'
 
  get '/customerservices',to: 'customerservices#new'

  get '/project',  to: 'projects#new'

  root 'sessions#new'

  post '/login',  to: 'sessions#create'
  
  get '/login',   to: 'sessions#new'

  delete '/logout',   to: 'sessions#destroy'

  get 'users/new'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/cloudservice.rb
class Cloudservice < ApplicationRecord
# has_many :projects, dependent: :destroy
  validates :code, uniqueness: { case_sensitive: false }
end

app/controllers/cloudservices_controller.rb
class CloudservicesController < ApplicationController
  before_action :logged_in_user
  before_action :set_cloudservice, only: [:show, :edit, :update, :destroy]

  # GET /cloudservices
  # GET /cloudservices.json
  def index
    @search = OpenStruct.new params[:search]
    @cloudservices = Cloudservice.all
    @cloudservices = build_search(@cloudservices, @search)

    @cloudservices = @cloudservices.order(expired_at: @search.expired_at) if @search.expired_at.present?
    @cloudservices
  end

  # GET /cloudservices/1
  # GET /cloudservices/1.json
  def show
  end

  # GET /cloudservices/new
  def new
    @cloudservice = Cloudservice.new
  end

  # GET /cloudservices/1/edit
  def edit
  end

  # POST /cloudservices
  # POST /cloudservices.json
  def create
    @cloudservice = Cloudservice.new(cloudservice_params)

    respond_to do |format|
      if @cloudservice.save
        format.html { redirect_to cloudservices_path, notice: 'Cloudservice was successfully created.' }
        format.json { render :show, status: :created, location: @cloudservice }
      else
        format.html { render :new }
        format.json { render json: @cloudservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cloudservices/1
  # PATCH/PUT /cloudservices/1.json
  def update
    respond_to do |format|
      if @cloudservice.update(cloudservice_params)
        format.html { redirect_to @cloudservice, notice: 'Cloudservice was successfully updated.' }
        format.json { render :show, status: :ok, location: @cloudservice }
      else
        format.html { render :edit }
        format.json { render json: @cloudservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cloudservices/1
  # DELETE /cloudservices/1.json
  def destroy
    @cloudservice.destroy
    respond_to do |format|
      format.html { redirect_to cloudservices_url, notice: 'Cloudservice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def build_search(records, search)
    if search.query.present?
      cols = [
        '`cloudservices`.`code` LIKE :query',
        '`cloudservices`.`vendor` LIKE :query',
      ]
      records = records.where(cols.join(" OR "), {query: "%#{search.query}%"})
    end

    records
  end

  def set_cloudservice
    @cloudservice = Cloudservice.find(params[:id])
  end

  def cloudservice_params
    params.require(:cloudservice).permit(:code, :vendor, :expired_at)
  end

  def logged_in_user
    unless logged_in?
    redirect_to login_url
    end
  end
end

app/helpers/cloudservices_helper.rb
module CloudservicesHelper
end

app/views/cloudservices/_form.html.erb
<!--
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"> 
  <title>水平表单</title>
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
-->


<%= form_for(cloudservice) do |f| %>
  <% if cloudservice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cloudservice.errors.count, "error") %> prohibited this cloudservice from being saved:</h2>

      <ul>
      <% cloudservice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<!--form class="form-horizontal" role="form">
  <div class="form-group">
	<label for="cloudserviceid" class="col-sm-2 control-label">cloudserviceid</label>
	<div class="col-sm-10">
	  <input type="text" class="form-control" id="cloudserviceid" 
			 placeholder="请输入服务器id">
	</div>
  </div>
  <div class="form-group">
	<label for="vendor" class="col-sm-2 control-label">vendor</label>
	<div class="col-sm-10">
    <input type="text" class="form-control" id="vendor" 
           placeholder="请输入供应商">
    </div>
  </div>
  <div class="form-group">
	<label for="expired_at" class="col-sm-2 control-label">expired_at</label>
	<div class="col-sm-10">
   	  <input type="text" class="form-control" id="expired_at" 
             placeholder="请输入到期时间">
	</div>
  </div>
</form>
 <!%= form_for(cloudservice) do |f| %>
  <div class="actions">
    <!%= f.submit %>
  </div>
<!% end %>
-->
  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  
  <div class="field">
    <%= f.label :vendor %>
    <%= f.text_field :vendor %>
  </div>

  <div class="field">
    <%= f.label :expired_at %>
    <%= date_select :cloudservice, :expired_at %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cloudservices/edit.html.erb
<h1>Editing Cloudservice</h1>

<%= render 'form', cloudservice: @cloudservice %>

<%= link_to 'Show', @cloudservice %> |
<%= link_to 'Back', cloudservices_path %>

app/views/cloudservices/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"> 
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.bootcss.com/foundation/5.5.3/css/foundation.min.css">
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">  
<script>
  $(function(){
    $("input[type=button]").click(function(){
      let txt=$("input[type=text]").val();
      if($.trim(txt) != ""){
        $("table tr:not('#theader')").hide().filter(":contains('"+txt+"')").show().css("background","white");
      }else{
      $("table tr:not('#theader')").css("background","#fff").show();
    }
  });
})
</script>

<style>

ul.side-nav {
  position: fixed;
  left: 25px;
  top: 60px;
  background-color: #eefaff;
}
 ul.side-nav {
   border-style:outset;
   border:1px solid #bbe1f1;
}
 ul.side-nav {
   padding-top:25px;
   padding-bottom:25px;
   padding-right:0px;
   padding-left:0px;
}

</style>

</head>

<body>
  <div class="page-header">
    <h1><center>Cloudservices</center></h1>
  </div>

<div class="panel-body">
  <%= form_for :search, method: :get do |f| %>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :query, '搜索条件' %>
        <%= f.text_field :query, value: @search.query %>
      </div>
      <div class="form-group">
        <input name="search[expired_at]" type="radio" value="desc" />
        <label>desc</label>
        <input name="search[expired_at]" type="radio" value="asc" />
        <label>asc</label>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary"><%= t("button.search") %></button>
      </div>
    </div>
  <% end %>
</div>

<ul class="side-nav">
 <li style="font-size: 1.5em;"><%= link_to "Customers",         customers_path    %></li>
 <li style="font-size: 1.5em;"><%= link_to "Cloudservices",     cloudservices_path %></li>
 <li style="font-size: 1.5em;"><%= link_to "Customerservers",   customerservers_path %></li>
 <li style="font-size: 1.5em;"><%= link_to "Projects",           projects_path %></li>
</ul>

<input type="text"></input>
<input type="button" value="搜索"></input>


<table id="myTable" class="table table-striped table-bordered table-hover tablesorter">
  <thead>
    <tr id="theader">
      <th>Code</th>
      <th>Vendor</th>
      <th>Expired at</th>
      <th colspan="3"</th>
    </tr>
  </thead>

  <tbody>
    <% @cloudservices.each do |cloudservice| %>
      <tr>
        <td><%= cloudservice.code %></td>
        <td><%= cloudservice.vendor %></td>
        <td><%= cloudservice.expired_at %></td>
        <td><%= link_to 'Show', cloudservice %></td>
        <td><%= link_to 'Edit', edit_cloudservice_path(cloudservice) %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cloudservice', new_cloudservice_path %>

</br>

<%= link_to 'Return to the home page', home_path      %>

</body>
</html>

app/views/cloudservices/new.html.erb
<h1>New Cloudservice</h1>

<%= render 'form', cloudservice: @cloudservice %>

<%= link_to 'Back', cloudservices_path %>

app/views/cloudservices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @cloudservice.code %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @cloudservice.vendor %>
</p>

<p>
  <strong>Expired at:</strong>
  <%= @cloudservice.expired_at %>
</p>

<%= link_to 'Edit', edit_cloudservice_path(@cloudservice) %> |
<%= link_to 'Back', cloudservices_path %> |
<%= link_to 'Destroy', @customer, method: :delete, data: { confirm: 'Are you sure?' } %>