config/routes.rb
Rails.application.routes.draw do

  resources :projects

  resources :customerservers

  resources :cloudservices

  resources :customers

  resources :users

  get '/home',     to: 'static_pages#home'

  get '/customers',   to: 'customers#new'

  get '/cloudservices', to: 'cloudservices#new'
 
  get '/customerservices',to: 'customerservices#new'

  get '/project',  to: 'projects#new'

  root 'sessions#new'

  post '/login',  to: 'sessions#create'
  
  get '/login',   to: 'sessions#new'

  delete '/logout',   to: 'sessions#destroy'

  get 'users/new'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/project.rb
class Project < ApplicationRecord
# belongs_to :cloudservice
  validates :code, uniqueness: { case_sensitive: false }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in_user
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:code, :name, :service, :start_time, :plan_complated_at, :actual_complated_at, :status, :url)
    end

    def logged_in_user
	  unless logged_in?
	    flash[:danger] = "Please log in."
	    redirect_to login_url
	  end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :service %>
    <%= f.text_field :service %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
	<%= date_select :project, :start_time %>
	<!--%= select_date Date.today, prefix: :start_time %-->
  </div>

  <div class="field">
    <%= f.label :plan_complated_at %>
    <%= date_select :project, :plan_complated_at %>
  </div>

  <div class="field">
    <%= f.label :actual_complated_at %>
    <%= date_select :project, :actual_complated_at %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.bootcss.com/foundation/5.5.3/css/foundation.min.css">

	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">  
	<script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/foundation/5.5.3/js/foundation.min.js"></script>
	<script src="https://cdn.bootcss.com/foundation/5.5.3/js/vendor/modernizr.js"></script>

<script>
  $(function(){
    $("input[type=button]").click(function(){
      var txt=$("input[type=text]").val();
        if($.trim(txt)!=""){
          $("table tr:not('#theader')").hide().filter(":contains('"+txt+"')").show().css("background","whi    te");
        }else{
          $("table tr:not('#theader')").css("background","#fff").show();
        }
   });
})
  49 </script>


<style>

ul.side-nav {
  position: fixed;
  left: 25px;
  top: 60px;
  background-color: #eefaff;
}
ul.side-nav {
  border-style:outset;
  border:1px solid #bbe1f1;
}
ul.side-nav {
  padding-top:25px;
  padding-bottom:25px;
  padding-right:0px;
  padding-left:0px;
}

</style>
</head>
<body>

<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><center>Projects</center></h1>
</div>

<ul class="side-nav">
  <li style="font-size: 1.5em;"><%= link_to "Customers",         customers_path    %></li>
  <li style="font-size: 1.5em;"><%= link_to "Cloudservices",     cloudservices_path %></li>
  <li  style="font-size: 1.5em;"><%= link_to "Customerservers",   customerservers_path %></li>
  <li  style="font-size: 1.5em;"><%= link_to "Projects",           projects_path %></li>
</ul>

<input type="text"></input>
<input type="button" value="搜索"></input>

<table class="table table-striped table-bordered table-hover tablesorter">

  <thead>
    <tr id="theader">
      <th>Code</th>
      <th>Name</th>
      <th>Service</th>
      <th>Start time</th>
      <th>Plan complated at</th>
      <th>Actual complated at</th>
      <th>Status</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.code %></td>
        <td><%= project.name %></td>
        <td><%= project.service %></td>
        <td><%= project.start_time %></td>
        <td><%= project.plan_complated_at %></td>
        <td><%= project.actual_complated_at %></td>
        <td><%= project.status %></td>
        <td><%= project.url %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>
<br>

<%= link_to 'Return to the home page',  home_path %>

</body>
</html>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @project.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Service:</strong>
  <%= @project.service %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @project.start_time %>
</p>

<p>
  <strong>Plan complated at:</strong>
  <%= @project.plan_complated_at %>
</p>

<p>
  <strong>Actual complated at:</strong>
  <%= @project.actual_complated_at %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>Url:</strong>
  <%= @project.url %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %> |
<%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' } %>